package com.example.leasing_zalyaeva_shift_2026.ui.theme

import androidx.compose.ui.graphics.Color

val BackgroundPrimary = Color(0xFFFFFFFF)
val BackgroundSecondary = Color(0XFFF3F4F6)
val BackgroundTertiary = Color(0xFFF9FAFB)
val BackgroundDisable = Color(0xFFF3F4F6)
val BorderExtraLight = Color(0xFFE3E5E5)
val BorderLight = Color(0xFFCED2DA)
val BorderMedium = Color(0xFF97A1AF)
val TextInvert = Color(0xFFFFFFFF)
val TextPrimary = Color(0xFF141C24)
val TextSecondary = Color(0xFF344051)
val TextTertiary = Color(0xFF637083)
val TextQuartenery = Color(0xFF97A1AF)
val TextError = Color(0xFFF64C4C)
val IndicatorWhite = Color(0xFFFFFFFF)
val IndicatorLight = Color(0xFFCED2DA)
val IndicatorMedium = Color(0xFF97A1AF)
val IndicatorNormal = Color(0xFF141C24)
val IndicatorError = Color(0xFFF64C4C)
val IndicatorAttention = Color(0xFFFFB219)
val IndicatorPositive = Color(0xFF40BF7F)
val BackgroundBrand = Color(0xFFDB0019)
val BackgroundBrandPrimary = Color(0xFFC10016)
val BackgroundHoverPrimary = Color(0xFFAD0014)
val BackgroundBrandExtraLight = Color(0xFFFF9696)
val TextBrandDisabled = Color(0xFFFF9BA6)
val IndicatorFocused = Color(0xFFDB0019)
val IndicatorFocusedAlternative = Color(0xFFDB0019)

